### ISSUE TITLE
X-Hero 3.43b bugs

### ISSUE THREAD

**Issue by peitschie** [EarthSalamander42/x_hero_siege#4]
* [x] Extra Ankhs vanish when entering the Muradin special arena. Usually I buy a few extra ankhs above the 3 you start with. This time, when the arena started, we lost all the extra ankhs, having just 3 in our inventory. If this is deliberate, would be handy to have it refunded, or a warning instead of the items just vanishing 😄 
* [ ] Minor: screen doesn't snap to special arena for other players when one commences (500/1000 kill arenas). Only the player being put in the arena has their screen move
* [ ] Special arena doesn't end when the player in it dies and is ejected. It still waits the full time to complete (this is pre-existing I think though)
* [x] Still seeing no countdown to the farming special event (i.e., the one before the event, indicating when it will start).
* [x] Minor: the lich's frost arrows skill has an attack slow of 0% listed in it's skill description

**Comment by peitschie** [comment]
On the up-side though, had no teleport-back-to-hero-select bugs in this one at all! Great work 🥇

**Comment by EarthSalamander42** [comment]
Yes lich's frost arrows is not supposed to slow attack speed!
For the extra ankhs, if they were in backpack, this bug is fixed now as ankhs can no longer be placed in backpack.
for the countdown bug that's because ramero and baristol uses special event timer (wich should be for muradin and farm event only), i'll fix this in next update!
